language: node_js
node_js:
  - "stable"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpam0g-dev
script: 
  - cd agile-IDM && pwd
  - cd agile-idm-commons && npm install
  - cd ../agile-idm-web-ui & npm install
  - cd ../agile-idm && npm install && npm test


